version: '3.8'
services:
  api:
    build: .
    ports:
      - 3001:3001
    depends_on:
      - pgdb
  pgdb:
    image: postgres
    restart: always
    ports:
      - 5433:5432
    environment:
      POSTGRES_DB: nestgraphql_db
      POSTGRES_USER: cnerylozada
      POSTGRES_PASSWORD: 123456
    volumes:
      - db:/var/lib/postgresql/data

volumes:
  db: